### ISSUE TITLE
카카오같이가치 카테고리 분류

### ISSUE THREAD

**Issue by im-shung** [2E2I/mamomo-server#27]
**카카오같이가치 주요 태그**
-

- 어린이: `아동|청소년`
- 여성: `여성`
- 어르신: `실버세대`
- 장애인: `장애인`
- 우리사회: `우리사회`
- 지구촌: `지구촌`
- 어려운이웃: `어려운이웃` , ( `이주민|다문화` , `모두의교육` )
- 동물: `동물` , ( `야생동물` )
- 환경: `환경`
 
**카테고리 분류 과정**
-
- 주요 태그를 갖고 있으면 해당 카테고리로 삽입하는 식으로 분류
- 문제점은 주요 태그를 여러 개 갖고 있는 페이지가 있음 -> **Q1. 카테고리를 중복으로 넣어도 괜찮은가??**
ex. [환경&우리사회](https://together.kakao.com/fundraisings/93613)
 
**카테고리 통일**
-
해피빈: `아동•청소년`, `어르신`, `장애인`, `다문화`, `지구촌`, `가족•여성`, `시민사회`, `동물`, `환경`, `기타`
카카오: `어린이`,  `어르신`, `장애인`, `어려운이웃`, `지구촌`,  `여성`, `우리사회`, `동물`, `환경`

**Q2. 카카오의  `어려운이웃`을  `어려운이웃`  ,`이주민|다문화` 로 나눠 각각 해피빈의 `기타`, `다문화`에 매칭하는 게 어떨까 싶음**

어차피 `이주민|다문화` 태그가 들어간 글에는  `어려운이웃` 태그가 없음 !  그냥 `어려운이웃` 카테고리에 세부 카테고리가 2개였던 것 

**Q3. 해피빈의 `가족•여성`은 어떻게 하면 좋을까요?**
`가족•여성`으로 냅두면 카카오의 `여성`이랑도 조금 차이가 나니까 ;-;
`가족`, `여성`으로 분리,  `가족`은 범위가 다양해서 각각 맞는 카테고리로 매칭..?? 

**Q4. 카테고리 이름 고정하기** 
아동•청소년 Vs 어린이 ??

**Comment by im-shung** [comment]
A1. 중복이 아니었으면 좋겠지만 그러면 분류 시 우선순위 기준을 뭘로 두어야 할지를 또 결정해야함 (그래도 중복되는 글이 얼마 없는 거 같아서 할 만 할지도,,??)
A3. 어린이, 어르신, 장애인, 어려운이웃, 다문화, 지구촌, 여성, 우리사회, 동물, 환경

**Comment by devyuseon** [comment]
### A1
흠 그런거면 복잡하겠지만
- `이주민|다문화` 는 `다문화`
- `모두의교육`은 `기타`
- `이주민|다문화` 와 `모두의교육`을 갖지 않는 `어려운이웃` 태그가 포함된 글은 `우리사회`와 매칭한다던가 하는게 나을듯? 중복되는것보단

### A2
A1에서 언급

### A3
나는 해피빈의 `가족•여성` 을 그냥 카카오의 `여성`이랑 같이 취급해야 할 것 같은데.
자동분류 시스템을 구현한다면  `가족•여성` 을 따로 분류 할 수 있겠지만 일단 지금은 그게 아니니까..

### A4
음 해피빈에 청년 관련 기부도 많아서 나는 `아동•청소년`에 한표

**Comment by im-shung** [comment]
### **A1**
아 Q1은 그런 얘기가 아니라 (`환경`+ `우리사회`)인 글을 말한 거 였어<- 아예 두 개의 카테고리에 들어있는! 

### **A3**
음 그럼 일단 같이 취급해볼게

### **A4**
오키 그럼 
`아동•청소년`, `어르신`, `장애인`, `어려운이웃`, `다문화`, `지구촌`, `여성`, `우리사회`, `동물`, `환경`

**Comment by devyuseon** [comment]
@im-shung 

### A1
그런거면 중복 괜찮을듯!!

### A4
Yaap 근데 그럼 `어려운 이웃`은 카카오만 노출되는건가?

**Comment by im-shung** [comment]
### **A4**
아닝 해피빈의 `기타 `를 `어려운 이웃`에 매칭하려고

**Comment by devyuseon** [comment]
@im-shung 👌👌

**Comment by im-shung** [comment]
테스트

**Comment by im-shung** [comment]
#32
