### ISSUE TITLE
회원가입 구현

### ISSUE THREAD

**Issue by devyuseon** [2E2I/mamomo-server#39]
`Client`<-**dto**->`controller(web)`-`service`-`repository`(**dao**)<-`domain`(**entity**)->`DB`

**User 엔터티 관련**
-
- Primary key 전략 
   - _Sequencial UUID_ 를 사용했음! - [참고한 사이트](https://devs0n.tistory.com/39) 
   - [Java Uuid Generator 라이브러리 사용함](https://github.com/cowtowncoder/java-uuid-generator)
   - build.gradle에서 `implementation 'com.fasterxml.uuid:java-uuid-generator:4.0.1'`
   - `UUID uuid = Generators.randomBasedGenerator().generate()`로 UUID 생성하기
 - create_date, modify_date는 mysql에서 데이터 삽입 시 자동으로 Timestamp 갱신하도록 설정함
    - [참고한 사이트](https://chinsun9.github.io/2020/11/11/insert-update%EC%8B%9C-%EC%9E%90%EB%8F%99%EA%B0%B1%EC%8B%A0-timestamp/)

**JPA 관련**
-
- `@Entity`나 `JpaRepository` 등 **JPA**로 구현은 했지만 
- 잘 모르는 상태🙃지금 강의 듣는 중... 

**회원가입 관련해서 앞으로 해야 할 것?**
-
- 좋아요, 관심 카테고리 관련 테이블 짜고 연관관계 매핑하기 
- 회원가입 시 검증하는 코드 추가하기 
- JPA 강의 듣고 코드 다듬기

**Comment by im-shung** [comment]
#47
