### ISSUE TITLE
회원 DB 설계 

### ISSUE THREAD

**Issue by im-shung** [2E2I/mamomo-server#40]
회원 가입 정보

> 아이디
> 비밀번호
> 닉네임
> 생년월일
> 성별
> 관심 기부 분야 

프로필 정보

> 아이디
> 닉네임
> 프로필 사진
> 생년월일
> 성별
> 관심 기부 분야
> 좋아요한 기부 리스트
> 기부 다이어리(? )

로그인 정보
> 아이디
> 비밀번호

이 세 개 고려해서 DB 구조 짜봅시당 ._.

**Comment by devyuseon** [comment]
![image](https://user-images.githubusercontent.com/67352902/158504664-9c6b848a-ad80-47f3-816f-b6f35ffc6d7b.png)
대충 한번 짜봤는데

- `회원 테이블`에서 회원 정보 저장
  -  `기부분야 테이블` PK 를 FK로 갖음
  -  `좋아요 리스트 테이블` PK를 FK로 갖음
  -  이때, 회원 정보가 삭제되면
      - `관심 기부분야 테이블` 삭제 **CASCADE**
      - `좋아요 리스트 테이블` 삭제 **CASCADE**
 - `관심 기부 분야 테이블` 에서 관심 기부 분야 리스트 저장
   - `기부분야 테이블` PK 를 FK로 갖는다.
   -  이 테이블이 삭제되더라도 기부분야 테이블은 삭제되지 않음
 - `기부 분야 테이블` 은 한 기부 분야에 대한 정보를 저장한다.
 - `좋아요 리스트 테이블` 은 `좋아요 테이블` 의 PK를 FK로 갖는다.
   - `좋아요 리스트 테이블`이 삭제되는것은 회원이 탈퇴한다는 의미
   - 따라서 이 테이블이 삭제되면 갖고있는 모든 좋아요 id의 `좋아요 테이블`은 삭제된다. **CASCADE**
 - `좋아요 테이블` 은 좋아요 정보를 저장한다.
   - `회원 테이블` 의 PK를 FK로 갖는다.
   - `좋아요 테이블`이 삭제되더라도 회원 테이블에 영향을 미치지 않는다.
   - 캠페인 id를 갖고 있으며, 이것을 가지고 ElasticSearch에서 검색을 해 캠페인 정보를 가져온다.


근데 의문점이 이렇게 매번 엘라스틱서치에서 검색을 해오는거면 너무 비효율적일거같은데
나중에 프로젝트 기능 개선할때, 세션이 유지될 동안이나 어떤 조건에서
ElasticSearch에서 읽어온 정보들을 **임시로** 저장하는 캐싱 기능이 있어야될듯?

**Comment by im-shung** [comment]
좋아요 리스트 테이블이면 될 것 같은데 좋아요 테이블이 필요할까??

**Comment by devyuseon** [comment]
해당 캠페인에 대해 좋아요 수가 몇개인지 검색해야하는데
이걸.. 효율적으로 해야해 전체를 불러올때는 구백 몇갠데 (크롤링 더해오면 늘어남)
매번 찾아야 되는,,

**Comment by im-shung** [comment]
음.. 좋아요 아이디가 캠페인이랑 1:1인거야?

**Comment by devyuseon** [comment]
좋아요 : 캠페인 = 1 : N

**Comment by devyuseon** [comment]
아? 반대 ㅋㅋ ㅜㅜ

ElasticSearch에서 한 캠페인이 좋아요 테이블 id 목록을 갖고 있어야 할까? 이런 뜻이여쓰

**Comment by im-shung** [comment]
아하 근데 그럼 넣기가 좀 복잡할 거 같아서

> 캠페인 id
> 캠페인에 좋아요 한 사용자 id 리스트 

이런 테이블을 하나 만들면 어때?

**Comment by devyuseon** [comment]
흠 그럼

A라는 사용자가 캠페인 목록을 불러올 때 모든 캠페인에 대한 그 테이블들에서 A가 있는지 검사
-> 이때 좋아요 갯수를 count 하려면 id 리스트 갯수는 쉽게 구할 수 O
A가 좋아요를 취소했을 경우엔 해당 테이블에서 회원 삭제
좋아요를 다시 누르면 해당 테이블에 다시 A를 add

괜찮을듯??

**Comment by im-shung** [comment]
오옹 좋아

**Comment by devyuseon** [comment]
![image](https://user-images.githubusercontent.com/67352902/158510128-55d2e033-1406-4530-a469-46b8441b703e.png)
이렇게 되는거 맞을까?

**Comment by im-shung** [comment]
ES는 안 건드리는 거지??

**Comment by im-shung** [comment]
움 저기 그림에서 ElsticSearch가 있길래 물어본 거 였오

**Comment by devyuseon** [comment]
옙 그렇긴 한데 이제 스프링에서 캠페인 클래스를 통째로 리턴하기보단 이제
DTO/DAO/Entity 를 나눠야 할 듯

**Comment by im-shung** [comment]
아 오키!

**Comment by im-shung** [comment]
gcp에 mysql 구축하는 거지?

**Comment by devyuseon** [comment]
음 아마두? 그리고, 회원가입 시에 비밀번호 그대로 저장하지 않고 암호화해서 하는게 좋을것같아 비밀번호가 그대로 들어가는건 좋지 않을듯?

찾아보면 Spring Security랑 연동할경우 비밀번호를 BCryptPasswordEncoder를 많이 쓰는데 시큐리티 5.0부턴 DelegatingPasswordEncoder를 권장하더라구 (찾아보니까 delegating~ 은 내부에 map으로 암호화 알고리즘 종류 매칭해주는것.. Delegating 이용해서 Bcrypt 쓰면될듯)

**Comment by im-shung** [comment]
아 맞아 난 해싱함수 찾아보고 있었는데 그런 방법도 있구만 

오키오키 

gcp에 mysql 직접 설치 / cloud sql 이용하기 
요 2가지 방법이 있는데 cloud sql은 자동 백업 기능 등을 제공하는데 돈이 더 많이 나가고 굳이 필요할까 싶기도 하고,,? 

gcp에 mysql 직접 설치로 할까?

**Comment by devyuseon** [comment]
그럽시당. (많이 해봤으니까)

**Comment by im-shung** [comment]
음 오키 고럼 gcp에는 나중에 설정하는 걸로

**Comment by devyuseon** [comment]
깃허브는 ctrl+ENTER가 올려지는거라 많이 헷갈림 ㅋㅋㅋ ㅜㅜ 오키

**Comment by im-shung** [comment]
![Mamomo](https://user-images.githubusercontent.com/67851738/158558054-af48e72e-05bc-4b29-b9aa-288063ad9cf5.png)

이건 어떤 거 같아?? 

좋아요(Like) 테이블에 캠페인 id, 사용자 id 이렇게 한 쌍씩 넣고 
캠페인의 좋아요 개수 -> 좋아요 테이블에서 캠페인 id 개수만 가져오기
사용자의 캠페인 좋아요 리스트 -> 좋아요 테이블이랑 사용자 id 조인해서 캠페인 id 리스트 가져오기 

관심분야(Fav_topic) 테이블도 사용자 id,  분야 id 한 쌍씩 넣고 
사용자의 관심분야 리스트 -> 관심분야 테이블이랑 사용자 id 조인해서 분야 리스트 가져오기

왜 이렇게 짰냐면 아까 그림으로 하려면 배열을 써야할 것 같은 ..? 
근데 쓰다보니까 언니가 생각한 게 이런 테이블인 거 같기도? 맞나영?

**Comment by devyuseon** [comment]
근데 이렇게 하면 좋아요 한 거 모아서 보기 힘들지 않아?

배열을 쓴 다기 보단(그보다 sql 자료형이 배열도 있었나..?) 해당(관심 분야 리스트, 좋아요 리스트) 테이블 PK 제외하고 관심 분야, 좋아요 id들 담으면 되는거구,

조인 횟수가 많아질수록 좋지 않을 것 같아서 🤔
좋아요 테이블은 각 사용자가 좋아요를 누른만큼 있을테니 조인 횟수가 너무 많아질듯
할 수 있으면 조인 하지 않고 바로 가져올 수 있는게 있으면 좋을 것 같아

**Comment by im-shung** [comment]
음 나도 지금 언니가 말하는 게 뭔지 모르겠어ㅋㅋㅋㅋ 만나서 얘기할까??

**Comment by im-shung** [comment]
![Mamomo](https://user-images.githubusercontent.com/67851738/158732935-05798042-1dd6-4d04-981c-bc664e230c58.png)

일단 이렇게 DB에 USERS 테이블만 만들어볼까?
