### ISSUE TITLE
회원가입 관련 Exception 처리 

### ISSUE THREAD

**Issue by im-shung** [2E2I/mamomo-server#62]
[여기](https://bcp0109.tistory.com/303)보고 따라했어 
[여기도](https://jeong-pro.tistory.com/195) 읽어보면 이해를 도울듯..! 

@devyuseon 예외처리할 일 있으면 참고햇 에러 코드 응답 형식 동일시켜야하니까! 

`controller/exception` 패키지
- `ErrorCode`: 핵심. 모든 예외 케이스를 이곳에서 관리함
- `CustomException`: 기본적으로 제공되는 Exception 외에 사용
- `ErrorResponse`: 사용자에게 JSON 형식으로 보여주기 위해 에러 응답 형식 지정

**Exception 처리하고 싶을 때!**
-
### 1. `ErrorCode.java`에 다음 형식으로 추가
- **에러코드이름(HttpStatus, 에러 메세지)**
- 이메일 중복 예외를 예시로 하면 다음과 같음 
```
// ErroCode.java
DUPLICATE_EMAIL(HttpStatus.CONFLICT, "이미 가입된 이메일입니다."),
```
### 2. Exception 사용
```
// UserService.java
if (userRepository.findByEmail(userDto.getEmail()).orElse(null) != null) {
            throw new CustomException(DUPLICATE_EMAIL);
}
```
```
// UserController.java
    @ExceptionHandler(value = CustomException.class)
    public ResponseEntity<ErrorResponse> handleCustomException(CustomException e) {
        log.error("handleCustomException throw CustomException : {}", e.getErrorCode());
        return ErrorResponse.toResponseEntity(e.getErrorCode());
    }
```

### 3. 실제 응답 
```
{
    "timestamp": "2022-03-26T00:38:24.7748532",
    "status": 409,
    "error": "CONFLICT",
    "code": "DUPLICATE_EMAIL",
    "message": "이미 가입된 이메일입니다."
}
```

**Comment by devyuseon** [comment]
근데 궁금한게 클라이언트에서 폼을 서버에 post로 전송했는데 뭔가 오류가 있어서 다시 작성해야 한다면

처음부터 다시 작성해야 하는거?

작성하던걸 유지시키려면 작성 했던 내용을 서버에서 다시 보내줘야 하는지 클라이언트에서 다시 처리해줘야 하는지?

기능상 중요하진 않지만.. 궁금해서

**Comment by im-shung** [comment]
뭔가 클라이언트쪽에서 폼 이용해서 처리할 수 있는 방법이 있지 않을까? 있을법한디..
