### ISSUE TITLE
API 문서 작성 

### ISSUE THREAD

**Issue by im-shung** [2E2I/mamomo-server#9]
사용 도구: **Spring Rest Docs**

**설정**
- 
- [x] build.gradle 설정

**캠페인 테스트 코드**
- 
- [x] 전체 리스트
- [x] 카테고리 리스트

**검색 테스트 코드**
- 
- [x] 태그
- [x] 검색

**Comment by devyuseon** [comment]
근데 이거 campaigns-deadline,default,latest 파라미터만 다르고 똑같은데 파라미터 설명만 주고 문서는 하나만 만드는게 맞지 않을까..???

**Comment by devyuseon** [comment]
그리고 /campaigns 에 request param 설명하는거 추가 해줘야 할듯!

**Comment by im-shung** [comment]
오키 땡큐!

**Comment by devyuseon** [comment]
앗 글구 테스트에 반환 객체가 `Campaign` 이라던가, `"campaigns"` 가 Array라던가 하는 테스트 검증 과정이 필요할듯! 😅

**Comment by im-shung** [comment]
오키오키 추가 해볼게!
